### ISSUE TITLE
Issue with date format

### ISSUE THREAD

**Issue by smutel** [stuartmccoll/gitlab-changelog-generator#25]
Hello,

When executing gitlab-changelog-generator, I get this issue:
`ValueError: time data '2019-04-15T08:58:4' does not match format '%Y-%m-%dT%H:%M:%S.%f'`

In DEBUG we can see the dates like:
```
'committed_date': '2019-04-15T08:58:44.000Z'
'authored_date': '2019-04-15T08:58:44.000Z'
```

Thanks for your help.

**Comment by stuartmccoll** [comment]
Hi,

Thanks for reporting - I'll take a look. Would you mind sending the command you used to run the utility, as well as the version you're using 👍?

**Comment by smutel** [comment]
Command used:
`changegen -i http://... -g smutel -p test -a 4 -b master 1.0 -t xxxxxx -v 1.0`

```
> pip3.6 show gitlab-changelog-generator | grep ^Version
> Version: 1.0.4
```

In calls.py, I replaced
```
response_json["committed_date"][:-6], "%Y-%m-%dT%H:%M:%S.%f"
...
x["committed_date"][:-6], "%Y-%m-%dT%H:%M:%S.%f"
```
by
```
response_json["committed_date"][:-1], "%Y-%m-%dT%H:%M:%S.%f"
...
x["committed_date"][:-1], "%Y-%m-%dT%H:%M:%S.%f"
```

Works better but I let you keep an eye on it.
Something strange is that the result contains one blank line (don't know if it is linked to this issue):

## v1.1 (2019-04-18)
* 2019-04-18 - Test2
* 2019-04-18 -

**Comment by stuartmccoll** [comment]
Where you've amended the slice from `[:-6]` to `[:-1]`, you'd also need to amend the string formatting being fed into the `datetime.datetime.strptime` call. So, your:

```
x["committed_date"][:-1], "%Y-%m-%dT%H:%M:%S.%f"
```

...would become:

```
x["committed_date"][:-1], "%Y-%m-%dT%H:%M:%S"
```

I've tested that and it seems to work. Let me know if you still see the blank line in the changelog being generated and I'll take a look at that separately.

😄

**Comment by smutel** [comment]
Hello,

I displayed the content of committed_date with logger.debug(response_json["committed_date"]).
The answer is 2019-04-18T12:26:08.000Z.
So ["committed_date"][:-1] is 2019-04-18T12:26:08.000.
This will not match "%Y-%m-%dT%H:%M:%S".

Need to keep "%Y-%m-%dT%H:%M:%S.%f", no ?
Do you manage the timezone currently ?

**Comment by stuartmccoll** [comment]
I'll take another look 🙂. Are you just trying to remove the 'Z' from the end and retain the microseconds, etc?

**Comment by smutel** [comment]
I just would like to make it work 😄 
In my environment, the format of the date sent by gitlab api is `2019-04-18T12:26:08.000Z`.
So after removing the 6 characters from the right as in your code we have `2019-04-18T12:26:0`.
Then I receive the error message:
`ValueError: time data '2019-04-18T12:26:0' does not match format '%Y-%m-%dT%H:%M:%S.%f'`

**Comment by stuartmccoll** [comment]
I think I _might_ have solved it - would you like me to push it up as a separate branch for you to test, or I can provide the code? It's only a couple of lines, but I'm considering using the dateutil library to make it so that I don't have to cater for specific timezone formats coming back from the GitLab API.

**Comment by smutel** [comment]
A separate branch is OK for me. I will checkout it and test it on my side. Thanks.

**Comment by stuartmccoll** [comment]
I've pushed up to a branch named `better-date-parsing` - it's rough, just want to see if it works for you.

You might need to `pip install python-dateutil` if you don't already have [python-dateutil](https://pypi.org/project/python-dateutil/).
